import Image from "next/image";
import { ArrowUpRight, Download, Mail, MapPin, MessageCircle, Phone, Quote } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { VideoHero } from "@/components/sections/video-hero";
import { Services } from "@/components/sections/services";
import { ProjectGallery } from "@/components/sections/project-gallery";
import { ContactForm } from "@/components/sections/contact-form";
import { HomepageEffects } from "@/components/sections/homepage-effects";
import { LogoCloud } from "@/components/ui/logo-cloud-4";
import { Marquee } from "@/components/ui/marquee";
import { HyperText } from "@/components/ui/hyper-text";
import { company, brands, sports } from "@/content/ast";
import { aboutParagraphs, brochureUrl, brochures, clientNames, homepageServices, testimonials } from "@/content/homepage";

const sportImages = ["/placeholders/jrd-tata.jpg", "/projects/kalinga.jpg", "/placeholders/sports-facility.jpg", "/video/hero-poster.webp", null, null, null, null];
const partnerLogos = [
  { src: "/brand/ligature.png", alt: "LigaTurf" },
  { src: "/brand/spurtan.png", alt: "Spurtan" },
  { src: "/brand/smartracks.png", alt: "SmarTracks" },
  { src: "/brand/gigatera.png", alt: "GigaTera" },
  { src: "/brand/humotion.png", alt: "Humotion" },
  { src: "/brand/poligras.png", alt: "Poligras" },
];

export function Homepage() {
  return <div className="ast-homepage"><a href="#main-content" className="skip-link">Skip to content</a><SiteHeader /><HomepageEffects /><main id="main-content">
    <VideoHero />
    <div className="brand-ribbon"><div className="page-container"><HyperText as="p" className="brand-positioning" startOnView duration={850}>Asia&apos;s Leading Sports Infrastructure Company</HyperText></div></div><div className="published-partners" aria-label="Brands featured on AST’s website"><LogoCloud logos={partnerLogos} /></div>
    <section id="about" className="section-pad about-section" data-nav-theme="light" aria-labelledby="about-title"><div className="page-container"><div className="about-layout"><div className="about-title"><p className="eyebrow"><span className="red-rule" />ABOUT US</p><h2 id="about-title">ABOUT<br /><span className="quiet-text">US.</span></h2><div className="about-image"><Image src="/placeholders/jrd-tata.jpg" alt="AST athletics track at JRD Tata Sports Complex, Jamshedpur" fill sizes="(max-width: 900px) 100vw, 35vw" /><span className="image-location"><MapPin size={13} />JAMSHEDPUR, INDIA</span></div></div><div className="about-copy"><p className="lead-copy">{aboutParagraphs[0]}</p><div className="about-detail">{aboutParagraphs.slice(1).map((paragraph) => <p key={paragraph.slice(0, 20)}>{paragraph}</p>)}</div><a href="#services" className="text-link">Discover what we do <ArrowUpRight size={17} /></a></div></div></div></section>
    <section className="stats-band" data-nav-theme="dark" aria-label="AST published figures"><div className="page-container stats-grid"><div><span className="stat-value">100<small>+</small></span><p>Installation of Hockey,<br />Tracks & Football Projects</p></div><div><span className="stat-value">1,000<small>K+</small></span><p>Square Meters<br />Sports Surfaces</p></div><div><span className="stat-value">20<small>Yr+</small></span><p>Experience</p></div></div></section>
    <section id="sports" className="section-pad sports-section" data-nav-theme="light" aria-labelledby="sports-title"><div className="page-container"><div className="section-heading"><div><p className="eyebrow"><span className="red-rule" />SPORTS SURFACES</p><h2 id="sports-title">SPORTS<br /><span className="quiet-text">SURFACES.</span></h2></div><p>Raise your game with our<br />world-renowned sports surfaces.</p></div><div className="sport-grid">{sports.map((sport, index) => <a className="sport-card" href={sport.source} key={sport.slug}>{sportImages[index] ? <Image src={sportImages[index]} alt="" fill sizes="(max-width: 640px) 50vw, 25vw" /> : <span className={`sport-court sport-court-${sport.slug}`} aria-hidden="true"><span /><span /><span /></span>}<span className="sport-number">0{index + 1}</span><span className="sport-card-label">{sport.name}<ArrowUpRight size={21} /></span></a>)}</div></div></section>
    <section id="products" className="section-pad products-section" data-nav-theme="light" aria-labelledby="products-title"><div className="page-container"><div className="section-heading"><div><p className="eyebrow"><span className="red-rule" />WORLD-RENOWNED BRANDS</p><h2 id="products-title">WORLD-RENOWNED<br /><span className="quiet-text">SPORTS SURFACES.</span></h2></div><p>Exclusive representative of<br />Polytan / SportGroup Germany.</p></div><div className="brand-grid">{brands.map((brand, index) => <article id={`brand-${brand.slug}`} className="brand-card" key={brand.slug}><div className="brand-logo-box">{brand.slug === "rekortan" || brand.slug === "ligaturf" ? <span className={`brand-wordmark wordmark-${brand.slug}`}>{brand.name}</span> : <Image src={`/brand/${brand.slug}.png`} alt={brand.name} width={210} height={95} sizes="210px" />}</div><div className="brand-card-meta"><span>0{index + 1}</span><h3>{brand.application}</h3><a href={brand.sportSlugs.includes("hockey") ? "https://ast-sports.com/hockey/" : brand.sportSlugs.includes("football") ? "https://ast-sports.com/football/" : "https://ast-sports.com/athletic-tracks/"} aria-label={`Explore ${brand.name}`}><ArrowUpRight size={22} /></a></div></article>)}</div></div></section>
    <section id="lighting" className="lighting-section" data-nav-theme="dark" aria-labelledby="lighting-title"><div className="lighting-image"><Image src="/services/lighting.jpg" alt="Sports lighting installation pictured on AST’s website" fill sizes="(max-width: 900px) 100vw, 55vw" /></div><div className="lighting-copy"><p className="eyebrow"><span className="red-rule" />SPORTS LIGHTING</p><h2 id="lighting-title">SPORTS<br />LIGHTING.</h2><p>{company.lighting}</p><p>All sports lighting has to be high-quality, totally reliable, efficient, and economic.</p><a href="#service-sports-lighting" className="ast-button ast-button-glass">Explore sports lighting <ArrowUpRight size={18} /></a><span className="lighting-partner">PANASONIC · JAPAN</span></div></section>
    <Services />
    <section id="maintenance" className="maintenance-band" data-nav-theme="dark" aria-labelledby="maintenance-title"><div className="page-container"><p className="eyebrow">CLEANING & MAINTENANCE</p><div className="maintenance-heading"><h2 id="maintenance-title"><span>FAIL & FIXED.</span><br />PREDICT & PREVENT.</h2><a href="#service-cleaning-maintenance" className="circle-link" aria-label="Explore cleaning and maintenance"><ArrowUpRight size={30} /></a></div><p>{homepageServices[7].description}</p></div></section>
    <ProjectGallery />
    <section id="testimonials" className="section-pad testimonials-section" data-nav-theme="light" aria-labelledby="testimonials-title"><div className="page-container"><div className="section-heading"><div><p className="eyebrow"><span className="red-rule" />TESTIMONIALS</p><h2 id="testimonials-title">TESTIMONIALS.</h2></div><p>The people behind<br />the projects.</p></div><div className="testimonial-marquee-shell"><Marquee pauseOnHover repeat={3} className="testimonial-marquee" tabIndex={0} aria-label="Client testimonials. Hover or focus to pause.">{testimonials.map((item) => <figure className="testimonial-card" key={item.name}><Quote size={27} aria-hidden="true" /><blockquote>“{item.quote}”</blockquote><figcaption><span className="client-avatar" aria-hidden="true">{item.name[0]}</span><div><strong>{item.name}</strong><span>{item.role}</span></div><span className="testimonial-line" /></figcaption></figure>)}</Marquee></div></div></section>
    <section id="clients" className="clients-section" data-nav-theme="light" aria-labelledby="clients-title"><div className="page-container clients-heading"><p className="eyebrow"><span className="red-rule" />OUR CLIENTS</p><h2 id="clients-title">OUR CLIENTS.</h2></div><div className="client-marquee" aria-label="AST client logos"><div className="client-track">{clientNames.map((name, index) => <div className="client-logo" key={name}><Image src={`/clients/client-${index + 1}.png`} alt={name} width={140} height={90} sizes="140px" /></div>)}<div className="client-duplicates" aria-hidden="true">{clientNames.map((name, index) => <div className="client-logo" key={name}><Image src={`/clients/client-${index + 1}.png`} alt="" width={140} height={90} sizes="140px" /></div>)}</div></div></div><div className="page-container"><details className="all-clients"><summary>View all 30 client logos</summary><div className="all-client-grid">{clientNames.map((name, index) => <div className="client-logo" key={name}><Image src={`/clients/client-${index + 1}.png`} alt={name} width={140} height={90} sizes="140px" /></div>)}</div></details></div></section>
    <section id="brochures" className="section-pad resources-section" data-nav-theme="light" aria-labelledby="brochures-title"><div className="page-container"><div className="section-heading"><div><p className="eyebrow"><span className="red-rule" />PRODUCT BROCHURES</p><h2 id="brochures-title">PRODUCT<br /><span className="quiet-text">BROCHURES.</span></h2></div><p>Explore the product catalogues<br />available on AST’s website.</p></div><div className="brochure-grid">{brochures.map((item) => <a href={brochureUrl(item.file)} target="_blank" rel="noopener noreferrer" className="brochure-card" key={item.file}><span className="pdf-tag">PDF</span><h3>{item.name}</h3><Download size={20} /></a>)}</div></div></section>
    <section className="build-cta" data-nav-theme="dark" aria-labelledby="build-title"><div className="page-container"><p className="eyebrow">FACILITATING EXCELLENCE</p><div><h2 id="build-title">WANT TO BUILD<br />A SPORTS FACILITY?</h2><a href="#contact" className="ast-button ast-button-white">Let’s talk <ArrowUpRight size={20} /></a></div></div></section>
    <section id="contact" className="section-pad contact-section" data-nav-theme="light" aria-labelledby="contact-title"><div className="page-container contact-layout"><div className="contact-details"><p className="eyebrow"><span className="red-rule" />GET IN TOUCH</p><h2 id="contact-title">GET<br /><span className="quiet-text">IN TOUCH.</span></h2><p className="contact-company">Advanced Sports Technologies LLP</p><address><a href="https://maps.google.com/?q=E-42+Okhla+Industrial+Area+Phase+II+New+Delhi+110020" target="_blank" rel="noopener noreferrer"><MapPin size={19} /><span>{company.contact.address}<br />{company.contact.city}</span></a><a href={company.contact.phoneHref}><Phone size={18} />{company.contact.phone}</a><a href={`mailto:${company.contact.email}`}><Mail size={18} />{company.contact.email}</a><a href={company.contact.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={19} />WhatsApp AST <ArrowUpRight size={15} /></a></address></div><div className="contact-form-panel"><h3>Have any queries?</h3><p>We’re here to help with your next sports facility.</p><ContactForm /></div></div></section>
  </main><footer className="site-footer"><div className="page-container"><div className="footer-top"><a href="#home" className="footer-logo"><Image src="/brand/ast-logo.png" alt="Advanced Sports Technologies" width={135} height={66} /></a><p>Facilitating Excellence.</p><a href="#home" className="text-link">Back to top <ArrowUpRight size={17} /></a></div><div className="footer-links"><div><h3>Sports</h3>{sports.map((sport) => <a href={sport.source} key={sport.slug}>{sport.name}</a>)}</div><div><h3>Services</h3>{homepageServices.map((service) => <a key={service.slug} href={`#service-${service.slug}`}>{service.name}</a>)}</div><div><h3>Explore</h3><a href="#about">About Us</a><a href="#products">Products</a><a href="#projects">Gallery</a><a href="#testimonials">Testimonials</a><a href="#clients">Our Clients</a><a href="#brochures">Brochures</a><a href="#contact">Contact</a></div><div className="footer-address"><h3>Get in Touch</h3><p>{company.contact.address}<br />{company.contact.city}</p><a href={company.contact.phoneHref}>{company.contact.phone}</a><a href={`mailto:${company.contact.email}`}>{company.contact.email}</a><a href={company.contact.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={14} /></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Advanced Sports Technologies LLP. All Rights Reserved.</span><span>DESIGNED FOR THE GAME.</span></div></div></footer><a href={company.contact.whatsapp} target="_blank" rel="noopener noreferrer" className="floating-whatsapp" aria-label="Contact AST on WhatsApp"><MessageCircle size={23} /></a></div>;
}
